knp_snappy:
    pdf:
        enabled:    true
        binary:     'export PATH=%kernel.project_dir%/bin/:$PATH;wkhtmltopdf'
        options:    []
    image:
        enabled:    true
        binary:     'export PATH=%kernel.project_dir%/bin/:$PATH;wkhtmltoimage'
        options:    []
